# Generated by Django 4.2.27 on 2026-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_material_price_remove_material_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='production_output',
            field=models.PositiveIntegerField(default=3800),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
