# Generated by Django 4.2.27 on 2026-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_price_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
