# Generated by Django 4.2.27 on 2026-07-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_production_profit_production_profit_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='stock_added',
            field=models.BooleanField(default=False),
        ),
    ]
