# Generated by Django 4.2.27 on 2026-07-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_production_stock_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='selling_price',
        ),
    ]
